#!/bin/sh
set -e

expected_checksum() {
	echo "4c5cc46abde9a90bdcc177fe19aae1265068b1c9"
}

actual_checksum() {
	shasum "$1" | awk '{print $1}'
}

main() {
	expected=$(expected_checksum)
	actual=$(actual_checksum "$1")
	if [ $expected == $actual ]; then
		exit 0
	else
		echo >&2 "'$1' has changed! now it's..."
		echo >&2 $actual
		exit 77
	fi
}

main "$@"
exit $?
