name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: dependencies
      run: sudo apt-get install check imagemagick libtool libmpc-dev libcairo2-dev libgd-dev libimlib2-dev
    - uses: actions/checkout@v2
    - name: make
      run: make SILENT= LIBTOOL_SILENT=
