name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: dependencies
      run: sudo apt install check imagemagick libtool libcairo2-dev libgd-dev libgd2-xpm-dev libmpc-dev libimlib2-dev
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make SILENT= LIBTOOL_SILENT=
